package sop_corba.GestionProductosPackage;

/**
* sop_corba/GestionProductosPackage/productoDTOHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from interface.idl
* lunes 10 de junio de 2024 12:06:12 AM COT
*/

public final class productoDTOHolder implements org.omg.CORBA.portable.Streamable
{
  public sop_corba.GestionProductosPackage.productoDTO value = null;

  public productoDTOHolder ()
  {
  }

  public productoDTOHolder (sop_corba.GestionProductosPackage.productoDTO initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = sop_corba.GestionProductosPackage.productoDTOHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    sop_corba.GestionProductosPackage.productoDTOHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return sop_corba.GestionProductosPackage.productoDTOHelper.type ();
  }

}
