package sop_corba.GestionProductosPackage;


/**
* sop_corba/GestionProductosPackage/ListProductosHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from interface.idl
* lunes 10 de junio de 2024 12:08:05 AM COT
*/

public final class ListProductosHolder implements org.omg.CORBA.portable.Streamable
{
  public sop_corba.GestionProductosPackage.productoDTO value[] = null;

  public ListProductosHolder ()
  {
  }

  public ListProductosHolder (sop_corba.GestionProductosPackage.productoDTO[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = sop_corba.GestionProductosPackage.ListProductosHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    sop_corba.GestionProductosPackage.ListProductosHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return sop_corba.GestionProductosPackage.ListProductosHelper.type ();
  }

}
