package sop_corba.GestionProductosPackage;


/**
* sop_corba/GestionProductosPackage/productoDTO.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from interface.idl
* lunes 10 de junio de 2024 12:08:05 AM COT
*/

public final class productoDTO implements org.omg.CORBA.portable.IDLEntity
{
  public String idUsuario = null;
  public String idProducto = null;
  public String tipoProducto = null;
  public String fechaEntrada = null;
  public String horaEntrada = null;
  public boolean estado = false;

  public productoDTO ()
  {
  } // ctor

  public productoDTO (String _idUsuario, String _idProducto, String _tipoProducto, String _fechaEntrada, String _horaEntrada, boolean _estado)
  {
    idUsuario = _idUsuario;
    idProducto = _idProducto;
    tipoProducto = _tipoProducto;
    fechaEntrada = _fechaEntrada;
    horaEntrada = _horaEntrada;
    estado = _estado;
  } // ctor

} // class productoDTO
