package sop_corba;


/**
* sop_corba/GestionProductosPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from interface.idl
* lunes 10 de junio de 2024 12:18:19 AM COT
*/

public abstract class GestionProductosPOA extends org.omg.PortableServer.Servant
 implements sop_corba.GestionProductosOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("registrarProducto", new java.lang.Integer (0));
    _methods.put ("consultarProducto", new java.lang.Integer (1));
    _methods.put ("listarProductos", new java.lang.Integer (2));
    _methods.put ("cambiarEstadoProducto", new java.lang.Integer (3));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // sop_corba/GestionProductos/registrarProducto
       {
         sop_corba.GestionProductosPackage.productoDTO objProducto = sop_corba.GestionProductosPackage.productoDTOHelper.read (in);
         boolean $result = false;
         $result = this.registrarProducto (objProducto);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 1:  // sop_corba/GestionProductos/consultarProducto
       {
         String codigo = in.read_string ();
         sop_corba.GestionProductosPackage.productoDTO $result = null;
         $result = this.consultarProducto (codigo);
         out = $rh.createReply();
         sop_corba.GestionProductosPackage.productoDTOHelper.write (out, $result);
         break;
       }

       case 2:  // sop_corba/GestionProductos/listarProductos
       {
         sop_corba.GestionProductosPackage.productoDTO $result[] = null;
         $result = this.listarProductos ();
         out = $rh.createReply();
         sop_corba.GestionProductosPackage.ListProductosHelper.write (out, $result);
         break;
       }

       case 3:  // sop_corba/GestionProductos/cambiarEstadoProducto
       {
         String codigo = in.read_string ();
         boolean nuevoEstado = in.read_boolean ();
         String $result = null;
         $result = this.cambiarEstadoProducto (codigo, nuevoEstado);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:sop_corba/GestionProductos:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public GestionProductos _this() 
  {
    return GestionProductosHelper.narrow(
    super._this_object());
  }

  public GestionProductos _this(org.omg.CORBA.ORB orb) 
  {
    return GestionProductosHelper.narrow(
    super._this_object(orb));
  }


} // class GestionProductosPOA
