package sop_corba;


/**
* sop_corba/ServidorInt.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from interface.idl
* domingo 9 de junio de 2024 11:29:34 PM COT
*/

public interface ServidorInt extends ServidorIntOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface ServidorInt
