package sop_corba.ServidorIntPackage;


/**
* sop_corba/ServidorIntPackage/datosUsuario.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from interface.idl
* domingo 9 de junio de 2024 06:00:17 PM COT
*/

public final class datosUsuario implements org.omg.CORBA.portable.IDLEntity
{
  public String nombre = null;

  public datosUsuario ()
  {
  } // ctor

  public datosUsuario (String _nombre)
  {
    nombre = _nombre;
  } // ctor

} // class datosUsuario
